import { readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';
import { offers } from '../server/public-site.mjs';
const root=resolve(import.meta.dirname,'..');
process.loadEnvFile(resolve(root,'.env.local'));
const quote=s=>"'"+s.replaceAll("'","''")+"'";
const user=process.env.DB_USER;
if(!/^[a-zA-Z0-9_]+$/.test(user))throw new Error('Invalid DB user');
let sql=readFileSync(resolve(root,'database/05-public-site.sql'),'utf8');
for(const [name,base] of offers) sql+=`\nINSERT INTO service_catalog(service_name,description,base_price,estimated_duration_minutes) VALUES (${quote(name)},'AC Care website service',${base},90) ON DUPLICATE KEY UPDATE service_name=VALUES(service_name);\n`;
for (const migration of ['06-booking-packages.sql','07-inventory-audit.sql','08-booking-email.sql','09-simple-services.sql','10-technician-cleaning.sql','11-customer-address-management.sql','12-customer-assistant.sql']) sql += '\n' + readFileSync(resolve(root,'database',migration),'utf8') + '\n';
for(const table of ['user_account','customer','service_address','aircon_unit','web_customer_profile','web_booking_details','web_legacy_import','booking_change_request'])sql+=`GRANT INSERT ON coolcare_service_app.${table} TO '${user}'@'%';\n`;
sql+=`GRANT UPDATE ON coolcare_service_app.booking TO '${user}'@'%';\n`;
for (const table of ['booking_service','booking_package','booking_email_outbox','inventory_transaction_revision','annual_booking_series','annual_booking_visit','work_order_cleaning_assessment','work_order_cleaning_assessment_revision']) sql+=`GRANT INSERT ON coolcare_service_app.${table} TO '${user}'@'%';\n`;
for (const table of ['booking_package','customer_subscription','booking_email_outbox','inventory_transaction']) sql+=`GRANT UPDATE ON coolcare_service_app.${table} TO '${user}'@'%';\n`;
sql+=`GRANT UPDATE (customer_id) ON coolcare_service_app.customer TO '${user}'@'%';\n`;
sql+=`GRANT UPDATE (full_name,phone) ON coolcare_service_app.user_account TO '${user}'@'%';\n`;
sql+=`GRANT UPDATE (address_label,address_line,postal_code,is_default,is_archived,replacement_address_id) ON coolcare_service_app.service_address TO '${user}'@'%';\n`;
sql+=`GRANT UPDATE ON coolcare_service_app.work_order_cleaning_assessment TO '${user}'@'%';\n`;
sql+=`GRANT UPDATE (updated_at) ON coolcare_service_app.work_order TO '${user}'@'%';\n`;
sql+=`GRANT INSERT, UPDATE ON coolcare_service_app.assistant_booking_draft TO '${user}'@'%';\n`;
const result=spawnSync('docker',['compose','--env-file','.env.local','exec','-T','database','sh','-c','exec mysql -uroot -p"$MYSQL_ROOT_PASSWORD"'],{cwd:root,input:sql,encoding:'utf8',windowsHide:true});
if(result.status!==0){console.error(result.stderr);process.exit(1);}console.log('Booking, package, inventory audit and email migrations are ready. Existing data preserved.');
